@host = http://localhost:5115

GET {{host}}/dinners
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiZDc2YjQ5NS0zNzc2LTRmM2MtOTlmNi1kNjJhZmQwYWNlMWYiLCJnaXZlbl9uYW1lIjoiQmF0dWhhbiIsImZhbWlseV9uYW1lIjoiVG95IiwianRpIjoiYTQ0OThmOTctZGMzYS00NDRkLWJjM2ItZDEwMzI5NjJmZjlkIiwiZXhwIjoxNzE0NjU2MzY3LCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.-GXwqmtLJ9M5nb-Pe2wxeP2ytV8ykN6P7gBb2Nc7zWk